version: '3'

services:
  django_gunicorn:
    volumes: 
      - static:/static
    env_file: 
      - .env
    build: 
      context: .
    ports: 
      - 8080:8080
  nginx:
    build: ./nginx
    volumes: 
      - static:/static
    ports: 
      - 80:80
    depends_on: 
      - django_gunicorn

volumes: 
  static:


  # web:
    # build: .
    # command: python manage.py runserver 0.0.0.0:8080
    # ports: 
    #   - 8080:8080
  